NKRO_ENABLE = yes            # USB Nkey Rollover
VELOCIKEY_ENABLE = no
BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
# AUTO_SHIFT_ENABLE = yes      # Auto Shift
#
LINK_TIME_OPTIMIZATION_ENABLE = yes
TAP_DANCE_ENABLE = no